# Generated by Django 4.2.4 on 2023-09-04 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(choices=[('documentar', 'Documentar'), ('reportes', 'Escribir reportes'), ('reunion', 'Reunión'), ('operacion', 'Operacion'), ('capacitacion', 'Capacitacion')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('inicial', 'Sin comenzar'), ('proceso', 'En proceso'), ('finalizado', 'Finalizada')], max_length=255)),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
                ('user_who_owns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
