# Generated by Django 4.2.4 on 2023-09-04 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskassigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigned',
            name='week',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='taskassigned',
            name='status',
            field=models.CharField(choices=[('proceso', 'En proceso'), ('finalizado', 'Finalizada')], max_length=255),
        ),
    ]
