# Generated by Django 4.2.4 on 2023-09-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskassigned_week_alter_taskassigned_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskassigned',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task'),
        ),
    ]
